openapi: 3.0.2
info:
  title: ioweyou.tech
  version: 1.1.1
paths:
  /api/login:
    summary: Endpoint to authenticate a user.
    get:
      description: >-
        Attempts to authenticate the user with the refresh JSON Web Token (if stored
        in the client's cookies) and redirects the user. Otherwise, the React login
        webpage will be returned.
      security:
        - userAuthenticated: []
      responses:
        "200":
          description: >-
            Returned with the react login page when refresh token authentication failed
            or did not take place.
        "302":
          description: >-
            Returned when refresh token authentication succeeded, redirecting to the
            dashboard React page or user's referrer URL (if within the application).
    post:
      description: >-
        Attempts authentication with the provided username and password in the
        requestBody. Sets the access_tokens cookie alongside a redirect request if
        successful.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Username of the account attempting to login.
                  example: jsmith
                password:
                  type: string
                  description: Plaintext password of the user.
                  example: hunter2
              required:
                - username
                - password
      responses:
        "302":
          description: >-
            Returned when the login was successful. This will set a JSON Web
            Token as a httpOnly cookie (with access & refresh tokens) and redirect
            the user to the referrer URL (if within the application) or the dashboard.
        "400":
          description: Returned when required requestBody was not provided, or invalid.
        "401":
          description: Returned when the password supplied is incorrect.
      tags:
        - Login
  /api/signup:
    summary: Endpoint to create a user.
    post:
      description: >-
        Attempts to create a user with the provided username, display name, and
        password in the requestBody. Sets the access_tokens cookie if successful.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Desired username for the to-be-created account.
                  maxLength: 16
                  example: jsmith
                display_name:
                  type: string
                  description: Desired display name for the to-be-created account.
                  maxLength: 50
                  example: John Smith
                password:
                  type: string
                  description: Plaintext password for the to-be-created account.
                  maxLength: 60
                  example: hunter2
              required:
                - username
                - displayName
                - password
      responses:
        "201":
          description: >-
            Returned when the user is successfully created. This will set a JSON
            Web Token as a httpOnly cookie (with access & refresh tokens).
        "400":
          description: Returned when required requestBody was not provided, or invalid.
        "422":
          description: Returned when the username is already taken.
      tags:
        - Signup
  /api/user:
    summary: Endpoint to view a user.
    get:
      description: >-
        Attempts to view the user information with the refresh JSON Web Token (if
        stored in the client's cookies).
      security:
        - userAuthenticated: []
      responses:
        "200":
          description: Returned user information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid user supplied
          content: {}
        "404":
          description: User not found
          content: {}
      tags:
        - User
    put:
      description: >-
        Attempts to update user if they are currently logged in
      tags:
        - User
      security:
        - userAuthenticated: []
      requestBody:
        description: Updated user object
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: Resource updated successfully
        "400":
          description: Invalid user supplied
          content: {}
        "404":
          description: User not found
          content: {}
    delete:
      description: >-
        Attempts to delete user if they are currently logged in
      tags:
        - User
      security:
        - userAuthenticated: []
      responses:
        "200":
          description: Resource deleted successfully
        "400":
          description: Invalid user supplied
          content: {}
        "404":
          description: User not found
          content: {}
  /api/user/requests:
    summary: Endpoint to view all requests created by a user.
    get:
      description: >-
        Attempts to view the requests created by a user with the refresh JSON Web Token (if
        stored in the client's cookies).
      security:
        - userAuthenticated: []
      responses:
        "200":
          description: Returned list of requests created by user.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/Request"
        "400":
          description: Invalid user supplied
        "404":
          description: User not found
      tags:
        - User
  /api/user/logout:
    summary: Logs out current logged in user session.
    get:
      description: >-
        Attempts to log user out of current session.
      parameters: []
      responses:
        default:
          description: Successful logout
          content: {}
      tags:
        - User
  /api/iou/owed:
    summary: Endpoint to view favours owed to a user.
    get:
      description: >-
        Attempts to view the favours owed to a user with the refresh JSON Web Token (if
        stored in the client's cookies).
      security:
        - userAuthenticated: []
      responses:
        "200":
          description: Returned list of favours owed to user.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/IOU"
        "400":
          description: Invalid user supplied
        "404":
          description: User not found
      tags:
        - IOU
  /api/iou/owe:
    summary: Endpoint to view favours a user owes.
    get:
      description: >-
        Attempts to view the favours a user owes with the refresh JSON Web Token (if
        stored in the client's cookies).
      security:
        - userAuthenticated: []
      responses:
        "200":
          description: Returned list of favours a user owes.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/IOU"
        "400":
          description: Invalid user supplied
        "404":
          description: User not found
      tags:
        - IOU
  /api/requests:
    summary: Endpoint to view all public requests.
    get:
      description: >-
        Attempts to view all requests created.
      responses:
        "200":
          description: Returned list of requests.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/Request"
        "400":
          description: Invalid user supplied
        "404":
          description: User not found
      tags:
        - Request
components:
  schemas:
    User:
      required:
        - username
      type: object
      properties:
        username:
          type: string
          example: jsmith
        display_name:
          type: string
          example: John Smith
      xml:
        name: User
    IOU:
      required:
        - id
        - item
        - giver
        - created_time
        - is_claimed
      type: object
      properties:
        id:
          type: integer
        item:
          type: object
          $ref: "#/components/schemas/Item"
        giver:
          type: object
          $ref: "#/components/schemas/User"
        receiver:
          type: object
          $ref: "#/components/schemas/User"
        parent_request:
          type: object
          $ref: "#/components/schemas/Request"
        proof_of_debt:
          type: integer
        proof_of_completion:
          type: integer
        created_time:
          type: string
          format: date-time
          example: "2020-03-09T22:18:26.625Z"
        claimed_time:
          type: string
          format: date-time
          example: "2020-03-09T22:18:26.625Z"
        is_claimed:
          type: boolean
          example: false
    Item:
      required:
        - id
        - display_name
      type: object
      properties:
        id:
          type: integer
        display_name:
          type: string
          example: Coffee
    Request:
      required:
        - id
        - author
        - details
        - created_time
        - is_completed
      type: object
      properties:
        id:
          type: integer
        author:
          type: object
          $ref: "#/components/schemas/User"
        completed_by:
          type: object
          $ref: "#/components/schemas/User"
        proof_of_completion:
          type: integer
        details:
          type: string
          example: Clean the fridge
        created_time:
          type: string
          format: date-time
          example: 2020-03-09T22:18:26.625Z
        completion_time:
          type: string
          format: date-time
          example: 2020-03-09T22:18:26.625Z
        is_completed:
          type: boolean
          example: false
  securitySchemes:
    userAuthenticated:
      type: apiKey
      description: >-
        Security scheme protecting endpoints that require a regular
        authenticated user account. Contains a refresh_token property and
        username property.
      name: access_tokens
      in: cookie
